//
// Generated file, do not edit! Created by opp_msgtool 6.0 from game_server.msg.
//

#ifndef __GAME_SERVER_M_H
#define __GAME_SERVER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class PlayerAction;
class GameStateUpdate;
/**
 * Class generated from <tt>game_server.msg:1</tt> by opp_msgtool.
 * <pre>
 * message PlayerAction
 * {
 *     string playerId;
 *     string action; // e.g., "move", "shoot"
 * }
 * </pre>
 */
class PlayerAction : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string playerId;
    omnetpp::opp_string action;

  private:
    void copy(const PlayerAction& other);

  protected:
    bool operator==(const PlayerAction&) = delete;

  public:
    PlayerAction(const char *name=nullptr, short kind=0);
    PlayerAction(const PlayerAction& other);
    virtual ~PlayerAction();
    PlayerAction& operator=(const PlayerAction& other);
    virtual PlayerAction *dup() const override {return new PlayerAction(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getPlayerId() const;
    virtual void setPlayerId(const char * playerId);

    virtual const char * getAction() const;
    virtual void setAction(const char * action);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PlayerAction& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PlayerAction& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>game_server.msg:6</tt> by opp_msgtool.
 * <pre>
 * message GameStateUpdate
 * {
 *     string gameState; // e.g., "player1_pos: (x,y)"
 * }
 * </pre>
 */
class GameStateUpdate : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string gameState;

  private:
    void copy(const GameStateUpdate& other);

  protected:
    bool operator==(const GameStateUpdate&) = delete;

  public:
    GameStateUpdate(const char *name=nullptr, short kind=0);
    GameStateUpdate(const GameStateUpdate& other);
    virtual ~GameStateUpdate();
    GameStateUpdate& operator=(const GameStateUpdate& other);
    virtual GameStateUpdate *dup() const override {return new GameStateUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getGameState() const;
    virtual void setGameState(const char * gameState);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GameStateUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GameStateUpdate& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline PlayerAction *fromAnyPtr(any_ptr ptr) { return check_and_cast<PlayerAction*>(ptr.get<cObject>()); }
template<> inline GameStateUpdate *fromAnyPtr(any_ptr ptr) { return check_and_cast<GameStateUpdate*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __GAME_SERVER_M_H

